### ISSUE TITLE
"View Details" on hero should be linked to listing

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#38]
"View Details" on the home page hero...

![Screen Shot 2022-10-12 at 12 21 36 PM](https://user-images.githubusercontent.com/2564452/195408188-ebd5fd35-a84f-46d2-b425-c827583d17d7.png)

should be linked to the non-modal view of the corresponding listing.

**Comment by emontes** [comment]
The problem is described in the following page https://github.com/leandrowd/react-responsive-carousel/issues/297

I already have the link working perfectly as seen in these lines.

![image](https://user-images.githubusercontent.com/1318017/195444777-b50d296d-738d-499a-8792-d869352870e9.png)

The problem is that the carousel script blocks them, I've been researching for a long time and I've found a solution that works.

**Comment by emontes** [comment]
After hours of research and none of the above working, I found that the conflict is changed by animationHandler="fade" , I removed it and everything worked like a charm (but we lost the cool fade effect).

**Comment by figart** [comment]
Thanks, Enrique. I think this can work, but we would need to slow down the transition... possible?

**Comment by emontes** [comment]
Absolutely with this variable transitionTime={3000} I can set the speed in miliseconds.  I left it at 3,000 (3 seconds) let me know if it seems good to you at that speed

**Comment by figart** [comment]
I think this looks good for now... will let client decide in the end whether the speed is ideal. Thank you!
